# Generated by Django 4.0.4 on 2022-05-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='main/img/pet/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('time_edit', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
