# Generated by Django 4.0.4 on 2022-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='main/img/pet/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='time_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
