# Generated by Django 4.0.4 on 2022-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pet_description_alter_pet_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-time_add', 'name', '-time_edit'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Кличка'),
        ),
    ]
