# Generated by Django 4.0.4 on 2022-05-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_species_person_alter_pet_options_pet_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.species', verbose_name='Биологический вид'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.person', verbose_name='Хозяин'),
            preserve_default=False,
        ),
    ]
